import Head from "next/head";
import Link from "next/link";
import { supabase } from "../utils/supabase";

import { useUser } from "../context/user";

export default function Home({ lessons }) {
  const { user } = useUser();

  console.log({ user });
  return (
    <div>
      <Head>
        <title>Saas application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto my-16 px-2">
        {lessons.map((lesson) => (
          <Link key={lesson.id} href={`/${lesson.id}`}>
            <a className="p-8 mb-4 rounded text-xl flex border border-gray-200">
              {lesson.title}
            </a>
          </Link>
        ))}
      </section>
    </div>
  );
}

export const getStaticProps = async () => {
  const { data: lessons } = await supabase.from("lesson").select("*");

  return {
    props: {
      lessons,
    },
  };
};
